#Profile: prod
restclient:
  url:
    jsonplaceholder-client: https://jsonplaceholder.typicode.com
    reqres-client: https://reqres.in/api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: admin
  flyway:
    enabled: false


springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false


domain:
  url: https://ait-experiment.sandbait.work/api


image:
  max-size-in-mega-byte: 3
