#Profile: dev
spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/test
    #username: postgres
    #password: admin
    url: jdbc:postgresql://localhost:30003/test
    username: postgres
    password: I7bcfi5aOC
    

restclient:
  url:
    reqres: https://reqres.in/api

filestorage:
  platform: local

localstorage:
  file-path: /srv/ait_spring_boot_template
  access-public: false
  public-base-url: http://localhost/

thumbnail:
  target-width: 300
  target-height: 300
  format: "JPG"
  quality: 1
  directory: /test