#Profile: dev
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: admin
    #url: jdbc:postgresql://dbs.sandbait.work:30034/test
    #username: postgres
    #password: I7bcfi5aOC
    

restclient:
  url:
    reqres: https://reqres.in/api

filestorage:
  platform: local

localstorage:
  file-path: C:\Users\devop\Downloads\AIT - Project - Lib\image
  access-public: false
  public-base-url: http://localhost/

thumbnail:
  target-width: 300
  target-height: 300
  format: "JPG"
  quality: 1